### ISSUE TITLE
ver. shared_preferences

### ISSUE THREAD

**Issue by marrullas** [lukepighetti/hydrated#7]
I do not know if it's an issue, but when I installed it, there was a compatibility error, because there is a new version shared_preferences, which was in my project previously

**Comment by lukepighetti** [comment]
@marrullas What version do you have installed and which version of hydrated gave compatibility errors?

**Comment by jcraven-worksight** [comment]
I'm also seeing this issue. Trying to update to version 0.5.1 of shared preferences while using hydrated version 1.2.1 I'm getting this error:
`Running "flutter packages get"...                  
Because hydrated 1.2.1 depends on shared_preferences ^0.4.3 and no versions of hydrated match >1.2.1 <2.0.0, hydrated ^1.2.1 requires shared_preferences ^0.4.3.`

**Comment by lukepighetti** [comment]
version bumped and available on pub

https://github.com/lukepighetti/hydrated/commit/e5a619c430c700b1de0aae1ff2070cfb9f566f4a
